frontend01:
  build: ./frontend
  links:
    - lb_api
  expose:
    - 80

frontend02:
  build: ./frontend
  links:
    - lb_api
  expose:
    - 80

lb_frontend:
  build: ./lb_frontend
  links:
    - frontend01
    - frontend02
  ports:
    - "80:80"
    - "70:70"
  expose:
    - 80
    - 70

api01:
  build: ./api
  expose:
    - 80

api02:
  build: ./api
  expose:
    - 80

lb_api:
  build: ./lb_api
  links:
    - api01
    - api02
  expose:
    - 80
    - 70
